apiVersion: v2
name: quarkus-simple
description: A helm chart for the basic app described on https://www.opensourcerers.org/2021/04/26/automated-application-packaging-and-distribution-with-openshift-part-12/
home: https://github.com/wpernath/quarkus-simple
type: application
version: 0.0.10
appVersion: "1.2.0"
sources:
    - https://github.com/dhanamjaya123/quarkus-simple
maintainers:
    - name: Dhanamjaya Rao
      email: dhanu8121@gmail.com
